version: "3.3"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./spring/.env
    environment:
      - MYSQL_ROOT_PASSWORD="root"
      - MYSQL_DATABASE=3306
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build:
      context: "spring"
      dockerfile: "./Dockerfile"
    restart: on-failure
    env_file: ./.env
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/tpstock?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"}'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  angular:
    build: 
      context : "crud-tuto-front"
      dockerfile: "./Dockerfile"
    container_name: angular
    ports:
      - 4200:4200
volumes:
  db: