version: "3.3"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
       MYSQL_ROOT_USER: Walid
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: tpstock
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
 