version: "3.3"

services:
 
   
  angular:
    build: 
      context : "crud-tuto-front"
      dockerfile: "crud-tuto-front/Dockerfile"
    container_name: angular
    ports:
      - 4200:4200
volumes:
  db: